---
sudo: required

services:
    - docker

before_install:
    - >
        if [ "$TRAVIS_BRANCH" == "master" ]; then
            # get last version
            export VER=$(git describe --tags --abbrev=0);

            # make images
            docker build --build-arg PHUSION_VERSION=$PHUSION_VERSION -t $DOCKER_USERNAME/apache-storm .;
            docker build --build-arg PHUSION_VERSION=$PHUSION_VERSION -t $DOCKER_USERNAME/apache-storm:$VER .;
        fi

    - >
        if [ "$TRAVIS_BRANCH" == "develop" ]; then
            docker build --build-arg PHUSION_VERSION=$PHUSION_VERSION -t $DOCKER_USERNAME/apache-storm:develop .;
        fi

script:
    - >
        if [ "$TRAVIS_BRANCH" == "master" ]; then
            docker run --rm --name storm $DOCKER_USERNAME/apache-storm storm version;
        fi

    - >
        if [ "$TRAVIS_BRANCH" == "develop" ]; then
            docker run --rm --name storm $DOCKER_USERNAME/apache-storm:develop storm version;
        fi

after_success:
    - if [ "$TRAVIS_BRANCH" == "master" ]; then
        docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        docker push $DOCKER_USERNAME/apache-storm:$VER;
        docker push $DOCKER_USERNAME/apache-storm;
      fi

    - if [ "$TRAVIS_BRANCH" == "develop" ]; then
        docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        docker push $DOCKER_USERNAME/apache-storm:develop;
      fi

notifications:
    email: false
    slack:
        secure: "NvSPKp7f0A46Qr34wHC0pLTm+1fUlvFVa+/zUJ0VQZ13CQVWl+LLiX5ENRJkEB4VMHVx5BRF9PUtiQvFpv6JqcPc68JUN9zkquBY48oMTki77IiTl02hE3JngZUXUaSuKfM6lOXDcDftyectuqBk9QUiieRfJ+lQ3fVinuhN5dYkvYpIXU9gYI+5J7wvXFPVr3sqGOLp1uYBgB3G59jzt2os0mcHjG1oQK2q/JuOC6K4LxNiymcpowhRN0y+ZFUnXqFjaApkGd9tkWD1R8ZG2VH1aXUdlukSXn8WqFd82D5PdzetAdhWW5aNLmLMYhKnvKfVlYfrjzqYeJVWtPgoWecC6+kEAZCbzzv5Um6t7HNrkX9F7E0Z3wq5WU30lEo595cxwVacN+s0NXyOvM3gghKo50AaX8i1/TzAuX9BAYkODvU2yvrE2Bjp+xyAeAZeQy5pK6MkCxyc6aebxMmbOx80mJoN5u7vxXFJASfm15xQoL9414pB+jLNBW033Ai1fwmQ0U3surKUXOf/c4U5xHrEXSqPArV7TWU/JhwVHpDN6qlcQCHw3oDElodnbHZX4S8itANOQzd+jqyzWxbhmleXyQYzkVF9mQKaoaUxoCnV7i81rUXgI+d+0IsHiI67VUPd54uVXXtIVEQtmRR8RXrT5pKUAxtQee5UQGibByI="
